### ISSUE TITLE
RougueDex 

### ISSUE THREAD

**Issue by SCHMIEDE110** [Admiral-Billy/PokeRogue-App-Android#2]
I would like to use your Windows.exe, but I always use the RogueDex add-on in the browser, this user interface that is always on in the game. Can you create a way to add it to your client? 

Would be all the happier <3 

Have a nice day man  - greetings from germany <3

**Comment by Admiral-Billy** [comment]
Hey there, this is the wrong repo to post this on, so sorry I missed it :P

Anyways, if someone can find an elegant way to actually integrate it, I'd happily do so, but as far as I know electron (despite being chromium-based) doesn't support the full extent of extensions and thus probably wouldn't work with RogueDex :(
